import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Suspense } from 'react'
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="manifest" href="/manifest.json" />
				<meta name="theme-color" content="#000000" />
				<link rel="apple-touch-icon" href="/favicon-512.png" />
			</head>
			<body className="bg-white w-full flex items-center md:block">
				<Toaster richColors />
				<Suspense fallback={<div>Loading...</div>}>
					{children}
				</Suspense>
			</body>
		</html>
	);
}
